/**
 * SalinTayo TTS wrapper.
 *
 * Providers:
 *
 * 1. Camb.AI
 *    - Existing female voice/provider.
 *    - Kept intact as the default female voice.
 *
 * 2. Edge TTS
 *    - Used for Angelo male voice.
 *    - Voice: fil-PH-AngeloNeural
 *    - Audio is generated by a backend using edge-tts.
 *
 * 3. Native Capacitor TTS
 *    - Fallback when Camb.AI fails or is unavailable.
 *
 * 4. Browser SpeechSynthesis
 *    - Final fallback on web.
 *
 * Existing callers continue using:
 *   speakText(text, options)
 *   cancelSpeech()
 *
 * Voice preference:
 *   salintayo_tts_voice
 *
 * Supported values:
 *   camb-female
 *   angelo-male
 */

import { Capacitor } from '@capacitor/core';
import {
  QueueStrategy,
  TextToSpeech,
} from '@capacitor-community/text-to-speech';

import { logBootStep } from './bootLogger';
import { getResolvedDialectLangCode, QCB_DIALECT_LANG_STORAGE_KEY, DIALECT_LANG_STORAGE_KEY } from './dialectPreference';

type DialectCode = string;

/* =========================================================
   PROVIDER / VOICE SETTINGS
   ========================================================= */

export type TtsVoiceId = 'camb-female' | 'angelo-male';

export const TTS_VOICE_STORAGE_KEY = 'salintayo_tts_voice';

export const DEFAULT_TTS_VOICE: TtsVoiceId = 'camb-female';

const CAMB_API_KEY =
  (import.meta.env.VITE_CAMB_API_KEY as string | undefined) ?? '';

const CAMB_TTS_VOICE_ID =
  Number(import.meta.env.VITE_CAMB_TTS_VOICE_ID ?? '') || 170787;

const CAMB_TTS_URL =
  'https://client.camb.ai/apis/tts-stream';

/**
 * Backend endpoint for Edge TTS.
 *
 * The backend should:
 *
 * POST JSON:
 * {
 *   "text": "...",
 *   "voice": "fil-PH-AngeloNeural"
 * }
 *
 * and return audio bytes.
 */
const EDGE_TTS_URL =
  (import.meta.env.VITE_EDGE_TTS_URL as string | undefined) ?? '';

const EDGE_TTS_VOICE =
  'fil-PH-AngeloNeural';

/* =========================================================
   VOICE PREFERENCE
   ========================================================= */

/**
 * Get the currently selected TTS voice.
 *
 * This is intentionally stored in localStorage so Profile,
 * Chat, Emergency Bubble, Quick Chat, and Auto-Mic can all
 * share one setting.
 */
export function getSelectedTtsVoice(): TtsVoiceId {
  try {
    const saved = localStorage.getItem(TTS_VOICE_STORAGE_KEY);

    if (saved === 'angelo-male') {
      return 'angelo-male';
    }

    if (saved === 'camb-female') {
      return 'camb-female';
    }
  } catch {
    // Ignore localStorage errors.
  }

  return DEFAULT_TTS_VOICE;
}

/**
 * Save the selected TTS voice.
 *
 * A custom event is emitted so currently-mounted components
 * can react immediately without requiring a page reload.
 */
export function setSelectedTtsVoice(voice: TtsVoiceId): void {
  try {
    localStorage.setItem(TTS_VOICE_STORAGE_KEY, voice);

    window.dispatchEvent(
      new CustomEvent('salintayo_tts_voice_changed', {
        detail: { voice },
      }),
    );
  } catch {
    // Ignore localStorage errors.
  }
}

/**
 * Human-readable labels for Profile/settings UI.
 */
export function getTtsVoiceLabel(voice: TtsVoiceId): string {
  switch (voice) {
    case 'angelo-male':
      return 'Angelo — Filipino Male';

    case 'camb-female':
    default:
      return 'Camb.AI — Female';
  }
}

/* =========================================================
   DIALECT / LOCALE
   ========================================================= */

const LANG_LOCALE_MAP: Record<string, string> = {
  en: 'en-US',
  fil: 'fil-PH',
  ceb: 'ceb-PH',
  ilo: 'ilo-PH',
  hil: 'hil-PH',
  war: 'war-PH',
  bik: 'bik-PH',
  pam: 'pam-PH',
  pag: 'pag-PH',
  tsg: 'tsg-PH',
};

function getDialectCodeForTts(): DialectCode {
  try {
    const code =
      localStorage.getItem(QCB_DIALECT_LANG_STORAGE_KEY) ??
      localStorage.getItem(DIALECT_LANG_STORAGE_KEY) ??
      getResolvedDialectLangCode();

    return (code || '').trim().toLowerCase() || 'en';
  } catch {
    return 'en';
  }
}

export function getTtsLocale(): string {
  // Legacy name retained for existing callers.
  const code = getDialectCodeForTts();

  return LANG_LOCALE_MAP[code] ?? 'en-US';
}

/* =========================================================
   DIALECT PRONUNCIATION RULES
   ========================================================= */

interface DialectRule {
  pattern: string;
  replacement: string;
}

const DIALECT_RULES: Record<string, DialectRule[]> = {
  // Avoid aggressive pronunciation hacks.
  // These rules are kept exactly conservative.
  fil: [],

  ceb: [],

  ilo: [],

  hil: [
    {
      pattern: '\\bnakaon ka na\\b',
      replacement: 'na-kaon ka na',
    },
    {
      pattern: '\\bnakaon ka\\b',
      replacement: 'na-kaon ka',
    },
    {
      pattern: '\\bnakaon\\b',
      replacement: 'na-kaon',
    },
    {
      pattern: '\\bkaon\\b',
      replacement: 'ka-on',
    },
    {
      pattern: '\\bpa ka\\b',
      replacement: 'pa ka',
    },
    {
      pattern: '\\bna ka na\\b',
      replacement: 'naka na',
    },
    {
      pattern: '\\bnakayon\\b',
      replacement: 'nakaon',
    },
    {
      pattern: '\\bpatay\\b',
      replacement: 'pati',
    },
  ],

  pag: [],

  en: [],
};

function getDialectRules(code: string): DialectRule[] {
  const normalized = (code || '').trim().toLowerCase();

  return DIALECT_RULES[normalized] ?? DIALECT_RULES.fil;
}

function applyDialectTransform(
  text: string,
  rules: DialectRule[],
): string {
  return rules.reduce((current, rule) => {
    try {
      return current.replace(
        new RegExp(rule.pattern, 'gi'),
        rule.replacement,
      );
    } catch {
      return current;
    }
  }, text);
}

/* =========================================================
   CAMB / AUDIO STATE
   ========================================================= */

let cambAbort: AbortController | null = null;
let cambAudioEl: HTMLAudioElement | null = null;
let cambAudioUrl: string | null = null;

let edgeAbort: AbortController | null = null;
let edgeAudioEl: HTMLAudioElement | null = null;
let edgeAudioUrl: string | null = null;

let voicesLoaded = false;

/* =========================================================
   DIALECT LABELS
   ========================================================= */

const DIALECT_LABEL: Record<string, string> = {
  en: 'English',
  fil: 'Filipino/Tagalog',
  ceb: 'Cebuano',
  ilo: 'Ilocano',
  hil: 'Hiligaynon',
  war: 'Waray',
  bik: 'Bicolano',
  pam: 'Kapampangan',
  pag: 'Pangasinan',
  tsg: 'Tausug',
};

/* =========================================================
   BROWSER VOICE FALLBACK
   ========================================================= */

async function waitForVoices(
  timeoutMs = 1000,
): Promise<SpeechSynthesisVoice[]> {
  if (
    typeof window === 'undefined' ||
    !window.speechSynthesis
  ) {
    return [];
  }

  if (voicesLoaded) {
    return window.speechSynthesis.getVoices();
  }

  const existing = window.speechSynthesis.getVoices();

  if (existing.length > 0) {
    voicesLoaded = true;
    return existing;
  }

  return new Promise((resolve) => {
    const onVoices = () => {
      clearTimeout(timeout);
      window.speechSynthesis?.removeEventListener(
        'voiceschanged',
        onVoices,
      );

      voicesLoaded = true;

      resolve(
        window.speechSynthesis?.getVoices() ?? [],
      );
    };

    const timeout = window.setTimeout(() => {
      window.speechSynthesis?.removeEventListener(
        'voiceschanged',
        onVoices,
      );

      voicesLoaded = true;

      resolve(
        window.speechSynthesis?.getVoices() ?? [],
      );
    }, timeoutMs);

    window.speechSynthesis?.addEventListener(
      'voiceschanged',
      onVoices,
    );
  });
}

const VOICE_QUALITY_HINTS: Record<string, string[]> = {
  'fil-PH': [
    'filipino',
    'tagalog',
    'rosa',
    'angeli',
    'maria',
    'google',
  ],

  'ceb-PH': [
    'filipino',
    'tagalog',
    'rosa',
    'angeli',
    'maria',
    'google',
  ],

  'ilo-PH': [
    'filipino',
    'tagalog',
    'rosa',
    'angeli',
    'maria',
    'google',
  ],

  'hil-PH': [
    'filipino',
    'tagalog',
    'rosa',
    'angeli',
    'maria',
    'google',
  ],

  'war-PH': [
    'filipino',
    'tagalog',
    'rosa',
    'angeli',
    'maria',
    'google',
  ],

  'bik-PH': [
    'filipino',
    'tagalog',
    'rosa',
    'angeli',
    'maria',
    'google',
  ],

  'pam-PH': [
    'filipino',
    'tagalog',
    'rosa',
    'angeli',
    'maria',
    'google',
  ],

  'pag-PH': [
    'filipino',
    'tagalog',
    'rosa',
    'angeli',
    'maria',
    'google',
  ],

  'tsg-PH': [
    'filipino',
    'tagalog',
    'rosa',
    'angeli',
    'maria',
    'google',
  ],

  'en-PH': [
    'philippines',
    'english',
    'google',
  ],

  'en-US': [
    'english',
    'google',
  ],
};

function pickVoiceForLocale(
  locale: string,
): SpeechSynthesisVoice | null {
  if (
    typeof window === 'undefined' ||
    !window.speechSynthesis
  ) {
    return null;
  }

  const voices = window.speechSynthesis.getVoices();

  if (!voices.length) {
    return null;
  }

  const normalizedLocale = locale.toLowerCase();
  const localeBase = normalizedLocale.split('-')[0];

  const qualityHints =
    VOICE_QUALITY_HINTS[locale] ?? [];

  const scored = voices
    .map((voice) => {
      const voiceLang =
        voice.lang?.toLowerCase() ?? '';

      const voiceName =
        voice.name?.toLowerCase() ?? '';

      let score = 0;

      if (voiceLang === normalizedLocale) {
        score += 120;
      }

      if (
        voiceLang.startsWith(`${localeBase}-`)
      ) {
        score += 80;
      }

      if (voiceLang === 'fil-ph') {
        score += 70;
      }

      if (voiceLang === 'en-ph') {
        score += 60;
      }

      if (voiceLang.startsWith('fil')) {
        score += 50;
      }

      if (voiceLang.startsWith('en')) {
        score += 20;
      }

      if (voice.localService) {
        score += 10;
      }

      if (voice.default) {
        score += 5;
      }

      for (const hint of qualityHints) {
        if (voiceName.includes(hint)) {
          score += 30;
          break;
        }
      }

      return {
        voice,
        score,
      };
    })
    .sort((a, b) => b.score - a.score);

  return scored[0]?.score > 0
    ? scored[0].voice
    : null;
}

/* =========================================================
   NATIVE / WEB LOCALE FALLBACKS
   ========================================================= */

const WEB_LOCALE_FALLBACKS: Record<
  string,
  string[]
> = {
  'ceb-PH': [
    'fil-PH',
    'en-PH',
    'en-US',
  ],

  'ilo-PH': [
    'fil-PH',
    'en-PH',
    'en-US',
  ],

  'hil-PH': [
    'fil-PH',
    'en-PH',
    'en-US',
  ],

  'war-PH': [
    'fil-PH',
    'en-PH',
    'en-US',
  ],

  'bik-PH': [
    'fil-PH',
    'en-PH',
    'en-US',
  ],

  'pam-PH': [
    'fil-PH',
    'en-PH',
    'en-US',
  ],

  'pag-PH': [
    'fil-PH',
    'en-PH',
    'en-US',
  ],

  'tsg-PH': [
    'fil-PH',
    'en-PH',
    'en-US',
  ],
};

async function resolveNativeLocale(
  locale: string,
): Promise<string> {
  try {
    const { supported } =
      await TextToSpeech.isLanguageSupported({
        lang: locale,
      });

    if (supported) {
      return locale;
    }
  } catch {
    // Continue to fallbacks.
  }

  const fallbacks =
    WEB_LOCALE_FALLBACKS[locale] ?? ['en-US'];

  for (const fallback of fallbacks) {
    try {
      const { supported } =
        await TextToSpeech.isLanguageSupported({
          lang: fallback,
        });

      if (supported) {
        return fallback;
      }
    } catch {
      // Continue trying.
    }
  }

  return 'en-US';
}

/* =========================================================
   NATIVE TTS
   ========================================================= */

async function speakNativeText(
  text: string,
  locale: string,
): Promise<void> {
  const lang =
    await resolveNativeLocale(locale);

  await TextToSpeech.stop().catch(
    () => undefined,
  );

  await TextToSpeech.speak({
    text,
    lang,
    rate: 0.92,
    pitch: 1,
    volume: 1,
    queueStrategy: QueueStrategy.Flush,
  });
}

/* =========================================================
   EDGE-TTS
   ========================================================= */

/**
 * Convert a backend response into a playable Blob.
 *
 * Preferred response:
 *   audio/mpeg
 *
 * Also supports:
 *   audio/wav
 *   audio/mp3
 *   application/octet-stream
 *
 * If your backend later returns JSON with base64 audio,
 * this helper can be extended without changing callers.
 */
async function responseToAudioBlob(
  response: Response,
): Promise<Blob> {
  const contentType =
    response.headers.get('content-type') ??
    '';

  if (
    contentType.includes('audio/') ||
    contentType.includes(
      'application/octet-stream',
    )
  ) {
    const buffer =
      await response.arrayBuffer();

    return new Blob([buffer], {
      type:
        contentType ||
        'audio/mpeg',
    });
  }

  /**
   * Optional JSON fallback.
   *
   * Supported shapes:
   *
   * {
   *   "audioBase64": "..."
   * }
   *
   * or:
   *
   * {
   *   "audio": "..."
   * }
   */
  if (
    contentType.includes(
      'application/json',
    )
  ) {
    const data =
      await response.json();

    const base64 =
      data?.audioBase64 ??
      data?.audio ??
      '';

    if (
      typeof base64 !== 'string' ||
      !base64.trim()
    ) {
      throw new Error(
        'Edge TTS backend returned JSON without audio data.',
      );
    }

    const cleanBase64 =
      base64.includes(',')
        ? base64.split(',').pop() ?? ''
        : base64;

    const binary =
      atob(cleanBase64);

    const bytes =
      new Uint8Array(binary.length);

    for (
      let i = 0;
      i < binary.length;
      i++
    ) {
      bytes[i] =
        binary.charCodeAt(i);
    }

    return new Blob(
      [bytes],
      { type: 'audio/mpeg' },
    );
  }

  throw new Error(
    `Unsupported Edge TTS response type: ${contentType || 'unknown'}`,
  );
}

/**
 * Speaks using the Edge TTS backend.
 *
 * Current voice:
 *   fil-PH-AngeloNeural
 */
async function speakEdgeAngelo(
  text: string,
  onStart: () => void,
  onEnd: () => void,
  onError: () => void,
): Promise<void> {
  if (!EDGE_TTS_URL) {
    throw new Error(
      'VITE_EDGE_TTS_URL is not configured.',
    );
  }

  edgeAbort =
    new AbortController();

  const signal =
    edgeAbort.signal;

  try {
    const response =
      await fetch(
        EDGE_TTS_URL,
        {
          method: 'POST',

          headers: {
            'Content-Type':
              'application/json',
          },

          body: JSON.stringify({
            text,
            voice: EDGE_TTS_VOICE,
          }),

          signal,
        },
      );

    if (!response.ok) {
      const errorText =
        await response
          .text()
          .catch(() => '');

      throw new Error(
        `Edge TTS HTTP ${response.status}: ${errorText}`,
      );
    }

    const audioBlob =
      await responseToAudioBlob(
        response,
      );

    if (!audioBlob.size) {
      throw new Error(
        'Edge TTS returned empty audio.',
      );
    }

    edgeAudioUrl =
      URL.createObjectURL(
        audioBlob,
      );

    edgeAudioEl =
      new Audio(edgeAudioUrl);

    edgeAudioEl.preload = 'auto';

    let startMeasured =
      false;

    edgeAudioEl.onplay = () => {
      if (!startMeasured) {
        startMeasured = true;
        onStart();
      }
    };

    edgeAudioEl.onended = () => {
      if (edgeAudioUrl) {
        URL.revokeObjectURL(
          edgeAudioUrl,
        );
      }

      edgeAudioUrl = null;
      edgeAudioEl = null;
      edgeAbort = null;

      onEnd();
    };

    edgeAudioEl.onerror = () => {
      if (edgeAudioUrl) {
        URL.revokeObjectURL(
          edgeAudioUrl,
        );
      }

      edgeAudioUrl = null;
      edgeAudioEl = null;
      edgeAbort = null;

      onError();
    };

    await edgeAudioEl.play();
  } catch (error) {
    if (signal.aborted) {
      return;
    }

    console.error(
      'Edge TTS error:',
      error,
    );

    logBootStep(
      `[TTS] Edge/Angelo failed: ${String(error)}`,
    );

    if (edgeAudioUrl) {
      URL.revokeObjectURL(
        edgeAudioUrl,
      );
    }

    edgeAudioUrl = null;
    edgeAudioEl = null;
    edgeAbort = null;

    throw error;
  }
}

/* =========================================================
   SPEAK API
   ========================================================= */

export interface SpeakTextOptions {
  onStart?: () => void;
  onEnd?: () => void;
  onError?: () => void;
}

/**
 * Speaks plain text using the voice selected in Profile.
 *
 * Selected voice:
 *
 *   camb-female
 *      -> Camb.AI
 *
 *   angelo-male
 *      -> Edge TTS / fil-PH-AngeloNeural
 *
 * If the selected provider fails:
 *
 *   Native device TTS
 *       ↓
 *   Browser SpeechSynthesis
 *
 * This preserves the existing fallback behavior.
 */
export function speakText(
  text: string,
  options?: SpeakTextOptions,
): void {
  const trimmed =
    text.trim();

  const ttsStartTime =
    performance.now();

  let ttsMeasured = false;

  const measureTtsStart =
    () => {
      if (ttsMeasured) {
        return;
      }

      ttsMeasured = true;

      const ms =
        performance.now() -
        ttsStartTime;

      console.log(
        `[PERF] TTS start latency: ${ms.toFixed(1)}ms`,
      );

      options?.onStart?.();
    };

  if (!trimmed) {
    options?.onEnd?.();
    return;
  }

  const selectedVoice =
    getSelectedTtsVoice();

  /* =======================================================
     ANGELO / EDGE TTS
     ======================================================= */

  if (
    selectedVoice ===
    'angelo-male'
  ) {
    cancelSpeech();

    void (
      async () => {
        try {
          await speakEdgeAngelo(
            trimmed,
            measureTtsStart,
            () => options?.onEnd?.(),
            () => options?.onError?.(),
          );
        } catch (error) {
          /**
           * Angelo failed.
           *
           * Fall back to the existing native/web TTS
           * system so the user still gets speech.
           */
          logBootStep(
            `[TTS] Angelo failed, falling back: ${String(error)}`,
          );

          try {
            const locale =
              getTtsLocale();

            if (
              Capacitor.isNativePlatform()
            ) {
              await speakNativeText(
                trimmed,
                locale,
              );

              measureTtsStart();
              options?.onEnd?.();

              return;
            }

            if (
              typeof window ===
                'undefined' ||
              !window.speechSynthesis
            ) {
              options?.onEnd?.();
              return;
            }

            await waitForVoices();

            window.speechSynthesis.cancel();

            const utter =
              new SpeechSynthesisUtterance(
                trimmed,
              );

            utter.lang =
              locale;

            utter.rate =
              0.92;

            utter.pitch =
              1;

            utter.onstart =
              () => {
                measureTtsStart();
              };

            utter.onend =
              () => {
                options?.onEnd?.();
              };

            utter.onerror =
              () => {
                options?.onError?.();
              };

            window.speechSynthesis.speak(
              utter,
            );
          } catch (fallbackError) {
            logBootStep(
              `[TTS] Angelo fallback failed: ${String(fallbackError)}`,
            );

            options?.onError?.();
          }
        }
      }
    )();

    return;
  }

  /* =======================================================
     CAMB.AI FEMALE VOICE
     ======================================================= */

  if (CAMB_API_KEY) {
    cancelSpeech();

    const code =
      getDialectCodeForTts();

    const rules =
      getDialectRules(code);

    const transformedText =
      applyDialectTransform(
        trimmed,
        rules,
      );

    const voiceId =
      CAMB_TTS_VOICE_ID;

    const language =
      (import.meta.env.VITE_CAMB_TTS_LANGUAGE as string | undefined) ??
      'en-us';

    const dialectLabel =
      DIALECT_LABEL[code] ??
      code.toUpperCase();

    cambAbort =
      new AbortController();

    const signal =
      cambAbort.signal;

    void (
      async () => {
        try {
          const requestBody = {
            text: transformedText,

            voice_id:
              voiceId,

            language,

            speech_model:
              'mars-instruct',

            user_instructions:
              `Speak naturally and fluently with a Philippine accent suitable for ${dialectLabel}. Pronounce Filipino-language words correctly. Keep an educational, friendly tutor voice. Avoid robotic pacing.`,

            output_configuration: {
              format: 'wav',
            },

            enhance_named_entities_pronunciation:
              true,

            voice_settings: {
              enhance_reference_audio_quality:
                false,

              maintain_source_accent:
                false,

              speaking_rate:
                0.95,

              apply_ref_loudness_norm:
                false,
            },

            inference_options: {
              temperature:
                0.55,

              inference_steps:
                60,

              speaker_similarity:
                0.7,

              stability:
                0.75,

              acoustic_quality_boost:
                false,
            },
          };

          const response =
            await fetch(
              CAMB_TTS_URL,
              {
                method: 'POST',

                headers: {
                  'Content-Type':
                    'application/json',

                  'x-api-key':
                    CAMB_API_KEY,
                },

                body: JSON.stringify(
                  requestBody,
                ),

                signal,
              },
            );

          if (!response.ok) {
            const errorText =
              await response
                .text()
                .catch(() => '');

            throw new Error(
              `Camb TTS HTTP ${response.status}: ${errorText}`,
            );
          }

          const arrayBuffer =
            await response.arrayBuffer();

          if (!arrayBuffer) {
            throw new Error(
              'Unexpected Camb TTS response',
            );
          }

          const audioBlob =
            new Blob(
              [arrayBuffer],
              {
                type: 'audio/wav',
              },
            );

          cambAudioUrl =
            URL.createObjectURL(
              audioBlob,
            );

          cambAudioEl =
            new Audio(
              cambAudioUrl,
            );

          let cambStartMeasured =
            false;

          cambAudioEl.onplay =
            () => {
              if (
                !cambStartMeasured
              ) {
                cambStartMeasured =
                  true;

                measureTtsStart();
              }
            };

          cambAudioEl.onended =
            () => {
              if (cambAudioUrl) {
                URL.revokeObjectURL(
                  cambAudioUrl,
                );
              }

              cambAudioUrl =
                null;

              cambAudioEl =
                null;

              cambAbort =
                null;

              options?.onEnd?.();
            };

          cambAudioEl.onerror =
            () => {
              if (cambAudioUrl) {
                URL.revokeObjectURL(
                  cambAudioUrl,
                );
              }

              cambAudioUrl =
                null;

              cambAudioEl =
                null;

              cambAbort =
                null;

              options?.onError?.();
            };

          await cambAudioEl.play();
        } catch (err) {
          if (signal.aborted) {
            return;
          }

          console.error(
            'Camb TTS error:',
            err,
          );

          logBootStep(
            `[TTS] Camb failed, falling back: ${String(err)}`,
          );

          cambAbort =
            null;

          cambAudioEl =
            null;

          if (cambAudioUrl) {
            URL.revokeObjectURL(
              cambAudioUrl,
            );
          }

          cambAudioUrl =
            null;

          /* ----------------------------------------------
             Existing native/web fallback
             ---------------------------------------------- */

          try {
            const locale =
              getTtsLocale();

            if (
              Capacitor.isNativePlatform()
            ) {
              try {
                await speakNativeText(
                  trimmed,
                  locale,
                );

                measureTtsStart();

                options?.onEnd?.();
              } catch (
                nativeErr
              ) {
                logBootStep(
                  `[TTS] native TTS fallback failed: ${String(nativeErr)}`,
                );

                options?.onError?.();
              }

              return;
            }

            if (
              typeof window ===
                'undefined' ||
              !window.speechSynthesis
            ) {
              options?.onEnd?.();
              return;
            }

            await waitForVoices();

            window.speechSynthesis.cancel();

            const utter =
              new SpeechSynthesisUtterance(
                trimmed,
              );

            utter.lang =
              locale;

            utter.rate =
              0.92;

            utter.pitch =
              1;

            utter.onstart =
              () => {
                measureTtsStart();
              };

            utter.onend =
              () =>
                options?.onEnd?.();

            utter.onerror =
              () =>
                options?.onError?.();

            window.speechSynthesis.speak(
              utter,
            );
          } catch (
            fallbackError
          ) {
            logBootStep(
              `[TTS] Web Speech fallback failed: ${String(fallbackError)}`,
            );

            options?.onError?.();
          }
        }
      }
    )();

    return;
  }

  /* =======================================================
     NO CAMB KEY / DEFAULT FALLBACK
     ======================================================= */

  const locale =
    getTtsLocale();

  if (
    Capacitor.isNativePlatform()
  ) {
    void speakNativeText(
      trimmed,
      locale,
    )
      .then(() => {
        measureTtsStart();
        options?.onEnd?.();
      })
      .catch(() => {
        options?.onError?.();
      });

    return;
  }

  if (
    typeof window ===
      'undefined' ||
    !window.speechSynthesis
  ) {
    options?.onEnd?.();
    return;
  }

  void (
    async () => {
      try {
        await waitForVoices();

        window.speechSynthesis.cancel();

        const utter =
          new SpeechSynthesisUtterance(
            trimmed,
          );

        utter.lang =
          locale;

        utter.rate =
          0.92;

        utter.pitch =
          1;

        const webFallbackLocales = [
          locale,
          ...(
            WEB_LOCALE_FALLBACKS[
              locale
            ] ?? ['en-US']
          ),
        ];

        const match =
          webFallbackLocales
            .map((l) =>
              pickVoiceForLocale(l),
            )
            .find(Boolean) ??
          null;

        if (match) {
          utter.voice =
            match;
        }

        utter.onstart =
          () => {
            measureTtsStart();
          };

        utter.onend =
          () => {
            options?.onEnd?.();
          };

        utter.onerror =
          () => {
            logBootStep(
              `[TTS] Web Speech fallback failed: utterance error for locale ${locale}`,
            );

            options?.onError?.();
          };

        window.speechSynthesis.speak(
          utter,
        );
      } catch (err) {
        logBootStep(
          `[TTS] Web Speech fallback failed: ${String(err)}`,
        );

        options?.onError?.();
      }
    }
  )();
}

/* =========================================================
   CANCEL SPEECH
   ========================================================= */

export function cancelSpeech(): void {
  /* Cancel Camb */
  try {
    cambAbort?.abort();
  } catch {
    // Ignore.
  }

  cambAbort = null;

  if (cambAudioEl) {
    try {
      cambAudioEl.pause();
      cambAudioEl.currentTime = 0;
    } catch {
      // Ignore.
    }

    cambAudioEl = null;
  }

  if (cambAudioUrl) {
    try {
      URL.revokeObjectURL(
        cambAudioUrl,
      );
    } catch {
      // Ignore.
    }

    cambAudioUrl = null;
  }

  /* Cancel Edge / Angelo */
  try {
    edgeAbort?.abort();
  } catch {
    // Ignore.
  }

  edgeAbort = null;

  if (edgeAudioEl) {
    try {
      edgeAudioEl.pause();
      edgeAudioEl.currentTime = 0;
    } catch {
      // Ignore.
    }

    edgeAudioEl = null;
  }

  if (edgeAudioUrl) {
    try {
      URL.revokeObjectURL(
        edgeAudioUrl,
      );
    } catch {
      // Ignore.
    }

    edgeAudioUrl = null;
  }

  /* Cancel native/device TTS */
  if (Capacitor.isNativePlatform()) {
    void TextToSpeech.stop()
      .catch(() => undefined);
  }

  /* Cancel browser TTS */
  if (
    typeof window !== 'undefined'
  ) {
    window.speechSynthesis?.cancel();
  }
}